#!/bin/bash

echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║                    EXEMPLO: programa0.gyh                     ║"
echo "║                  (com erro de gramática ENTO)                 ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
echo ""

echo "📄 Conteúdo do arquivo programa0.gyh (linhas relevantes):"
echo "───────────────────────────────────────────────────────────────"
echo ""
echo "  12 | SE num1 > num2 ENTAO      ✓ Correto"
echo "  13 |    INI"
echo "  14 |       aux := 2. 4+3-4+5-6*5-1.6"
echo "  15 |       num2 := num1"
echo "  16 |       num1 := aux"
echo "  17 |    FIM"
echo "  18 | SE num1 > num3 E num2 <= num4 E num1 > 3 OU num2 != num4 ENTO"
echo "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ✗ ERRO"
echo "  19 |    INI"
echo "       ^ Falta 'A' - ENTO deveria ser ENTAO"
echo ""

echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║              SAÍDA DO COMPILADOR GYH"
echo "╚═══════════════════════════════════════════════════════════════╝"
echo ""

mvn exec:java -Dexec.mainClass="main" -Dexec.args="src/testes/testeLexico/programa0.gyh" -q 2>&1

echo ""
echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║                        ANÁLISE                                ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
echo ""
echo "✅ O compilador DETECTOU corretamente:"
echo ""
echo "  1. ERRO LÉXICO na linha 15, posição 14:"
echo "     Token desconhecido: '.'"
echo "     Causa: '2. 4' (número real inválido)"
echo ""
echo "  2. ERRO LÉXICO na linha 19, posição 58-60:"
echo "     Token desconhecido: 'N', 'T', 'O'"
echo "     Causa: 'ENTO' não é uma palavra-chave válida"
echo "     Esperado: 'ENTAO'"
echo ""
echo "❌ Compilação FALHADA com sucesso!"
echo "   (O arquivo .c NÃO foi gerado)"
echo ""
